### ISSUE TITLE
Add tree folder structure for 'available component' and 'available mockdata' on Step Definition

### ISSUE THREAD

**Issue by yemo** [TradeMe/tractor#100]
This issue raised from #25 .

'available component' and 'available mockdata' become a huge list. it will be better to have tree folder structures, allow expand and collapse folders on the page.

**Comment by Galileo1** [comment]
@jonoelkin @yemo - as per my understanding adding collapsing function isn't going to enhance the readability/usability of the page.Can you please make me understand what you want out of this issue?

**Comment by jonoelkin** [comment]
Idea is that if the component and mock data gets too massive a list, it is hard to find what you are after. More of an issue around mock data than components though/.

**Comment by phenomnomnominal** [comment]
Why not just autocomplete?

**Comment by jonoelkin** [comment]
Auto complete would be good

**Comment by Galileo1** [comment]
@jonoelkin can u please check this in v0.9.5?
