### ISSUE TITLE
Selecting element by text is not working 

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#102]
When trying to use element(by.cssContainingText) it is not working. It appears that when you save the file we are adding '*', at the beginning 

this.loginButton = element(by.cssContainingText('*', 'button, Log in'));

also tried this

this.loginButton = element(by.css('button')).element(by.cssContainingText('*', 'Log in'));

What it should be:

this.loginButton = element(by.cssContainingText('Log in')); and we should have to stipulate the CSS before adding the by Text step

**Comment by Galileo1** [comment]
looking into it.

**Comment by Galileo1** [comment]
the changes for this are sitting in branch. Need help from @phenomnomnominal to fix unit testcases.
