### ISSUE TITLE
IsEnabled = false checking not working

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#105]
In many cases an element is visible on a page, but it is not enabled (it is greyed out) because some validation has occurred or some data is missing in order for it to become enabled. It is quite a common ux tool in preview.

At the moment we attempt to do some testing to ensure a button is not enabled until it should be. We attempt to do this by using an action in the component of "IsEnabled" and then in the "then" step definition using "equals false" to confirm if the button is indeed disabled when we expect it to be.

This function does not appear to be working.

**Comment by jonoelkin** [comment]
We think it may be doing more of a 'isDisplayed' than a "isEnabled"

**Comment by Galileo1** [comment]
pull request https://github.com/TradeMe/tractor/pull/107 created.
