### ISSUE TITLE
Duplicate named step definitions

### ISSUE THREAD

**Issue by CameronClark** [TradeMe/tractor#106]
The way I have managed to do so is:
1. Have a previously created step definition, lets say for example "_I am on the home page_"
2. The already created definition can be anywhere, but in this example it was in a sub folder, eg. (Jobs/WHEN/When I am on the home page)
3. I go to create a new feature, in which I want to use this already created step definition.
4. I add a step in my feature that is named **exactly** the same in the hopes tractor will pick up the already created step def so I don't have to duplicate it.
5. Tractor creates a new empty step of the **exact** same name, and uses that one instead.
6. Deleting the newly created empty step definition and running the feature again will use the previously created one.

I think it is a fundamental issue to allow step definitions to use the same name. I normally have a lot of issues with Tractor when it does this :(

![tractorpls](https://cloud.githubusercontent.com/assets/5000423/19289972/c06fa05c-9069-11e6-8d55-e51a39089638.png)

**Comment by Galileo1** [comment]
@CameronClark  acknowledging this. definitely a problem.

**Comment by Galileo1** [comment]
@CameronClark I analysed and tried to replicate the above steps and I can say that tractor doesn't create duplicate step-def for an existing one.But I do acknowledge that it doesn't refreshes the view if you delete/move the step-def from windows explorer but it does update the view if you handle file movement/deletion from tractor UI. And the above could be the result of that.I my understanding tractor should read from the disk everytime even though it's costly in terms for i/o calls but I will chat to @phenomnomnominal about it.

**Comment by CameronClark** [comment]
I think this is fixed. Haven't had it happen since :)
