### ISSUE TITLE
Updating a component action breaks the link between step def and component

### ISSUE THREAD

**Issue by CameronClark** [TradeMe/tractor#109]
Unsure if this is deliberate, but if:
1. I have a component with an action
2. I have a step definition that uses this aforementioned action
3. I rename the action
4. The step definition will no longer have that action, it breaks the association between them.

As far as I know, this is different from the behavior of changing elements/locators, but I think actions should probably follow suit?

**Comment by phenomnomnominal** [comment]
Duplicate of #37
