### ISSUE TITLE
Can't init; `env: node\r: No such file or directory`

### ISSUE THREAD

**Issue by BevanR** [TradeMe/tractor#110]
Following the instructions in README.md, I can't get past `tractor init`.

I get `env: node\r: No such file or directory` when I run it in the root of an NG2 app, using node 6.9.1 (latest lts).

**Comment by BevanR** [comment]
Same issue using node 0.10.48 (I got 0.10 from package.json)

**Comment by phenomnomnominal** [comment]
I'm guessing OS X?

**Comment by BevanR** [comment]
Yessir

**Comment by phenomnomnominal** [comment]
I'm guessing that this is because the file has Windows line endings in it... I'll take a look. Also, worth noting that this won't work with NG2 yet, but it's not far off.

**Comment by phenomnomnominal** [comment]
@BevanR just looking through some old issues - we're now up and running with Angular with `tractor@latest`. I'm pretty sure this is fixed there too.

**Comment by BevanR** [comment]
Confirmed.
