### ISSUE TITLE
Tractor does not allow saving a string with double quote via the interface

### ISSUE THREAD

**Issue by priyray** [TradeMe/tractor#113]
When adding double quote in Expected result field of step definition area , it would not allow me to save it.
Have to force the quotes via visual code editor
Saving the below expected result 
![image](https://cloud.githubusercontent.com/assets/9528557/21790550/0c327798-d742-11e6-8387-f0afdad1dbd0.png)
Automatically reverts back the tractor step definition to below 
![image](https://cloud.githubusercontent.com/assets/9528557/21790588/45a5fd9c-d742-11e6-8657-d35af5ec7311.png)

**Comment by phenomnomnominal** [comment]
yeah this is probably a bug, but it looks like your actions should be "get width" and "get height" and they should use the getAttribute function.

**Comment by priyray** [comment]
Yes Craig I used getAttribute :) , but was just playing with getOuterHtml to combine the assertion in one step and noticed the double quote does not work. It works , if I force the quote via the IDE edit (Webstorm/Visual code) though .So I thought I will keep it as a "nice to have" fix.

**Comment by phenomnomnominal** [comment]
Apparently I fixed this at some point!
