### ISSUE TITLE
In tractor version 

### ISSUE THREAD

**Issue by priyray** [TradeMe/tractor#114]
In tractor version 0.9.2 , I have to select an existing step declaration multiple times from the suggested list before tractor is able to register the selection . Kind of slows down the flow , see below gif
![tractorstepdedfselectionissue](https://cloud.githubusercontent.com/assets/9528557/21793232/42bfde92-d754-11e6-9dab-e8fff36b7e59.gif)

**Comment by Galileo1** [comment]
I thought we were way past this problem since no one reported it but I will have a look into the code and probably fix this in next version.Thanks.

**Comment by Galileo1** [comment]
Hey @priyray, Can you please test this in 0.9.5 and close this issue.

![improved autocomplete on feature page](https://cloud.githubusercontent.com/assets/9716232/22133133/655ec310-df23-11e6-8fc3-bc87c05ed181.gif)

**Comment by priyray** [comment]
Woohoo @Galileo1 Varun the legend  - works like a charm in  0.9.5 , thanks very much 💃
