### ISSUE TITLE
Moving mock data files & step definitions to new folders break the tests

### ISSUE THREAD

**Issue by priyray** [TradeMe/tractor#117]
**Steps to reproduce** 

1. Created a mock data file 
2. Call that from a step definition , commit the changes 
3. Move the mock data file to a new destination folder via Tractor UI 
4. Move the step definition file to a new new destination folder via Tractor UI 
5. Commit the changes 
6. Try running the feature from Feature tab

**Expected** 
Feature tests should run without any problem 

**Actual**
Once the files are moved between folders - feature tests are unable to find the mock data files and stops .
User has to re attach the mock data files to related step definition steps

**Comment by phenomnomnominal** [comment]
Should be fixed by https://github.com/phenomnomnominal/tractor-plugin-mock-requests/commit/70b078a49cfb98a32ea4da2d0d756c2d04d0d833#diff-ff07cf71d7cec801e7a0c61d06310cacR24
