### ISSUE TITLE
Ability to add step defs anywhere in the scenario without having to use drag and drop 

### ISSUE THREAD

**Issue by priyray** [TradeMe/tractor#118]
When I am  adding a given step to a really huge & complex scenario under feature area (e.g.  Property Search & Refine)  , adding a new step declaration adds it to the bottom of the current  step defs . Then I have to drag and drop the current step to the top section . The drag and drop is not very smooth , and the item when dragged to the header area of the page does not allow the page to scroll up automatically . This means this drag and drop action unless  handeled  very carefully, reinstates the newly added step to bottom of the pile again . 

Will be good to have an ability to add step defs anywhere in the scenario without having to use drag and drop

**Comment by phenomnomnominal** [comment]
Closing this as `@tractor-plugins/features` is now deprecated.
