### ISSUE TITLE
Tractor files shouldn't reference .orig files

### ISSUE THREAD

**Issue by juliaws** [TradeMe/tractor#121]
Tractor wouldn't run due to step definitions referencing .orig files.  It shouldn't be allowed to do this.

The step def file contained a reference to a component that was called xxxxx.component.js.orig
The step def file should only ever reference xxx.component.js

**Comment by phenomnomnominal** [comment]
Not sure how to repro this one. I think it should be impossible with the changes I've made to tractor-file-structure
