### ISSUE TITLE
When you run multiple scenario's, data is being cached. 

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#125]
Given you have multiple scenarios, for example successful login and failed login. 
When you run those tests, the second tests always fail's as it is using the cached data from the first test.

So the expectation is that i should not be logged in as i am using invalid login details for the second test. 

Strange thing, is if you reorder the the test, then both tests pass.

**Comment by Galileo1** [comment]
I think we are clearing up session & local storage. as well as session cookies after every scenario. Isn't it?
