### ISSUE TITLE
Tag's are not displaying in UI

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#127]
After tagging a feature/scenario 
The tag is not displaying in the UI

The tag is displaying in the file, just not in the UI

**Comment by phenomnomnominal** [comment]
Fixed in https://github.com/phenomnomnominal/tractor-plugin-features/commit/dcf2abc5611f0cdc2bc4bdb2e341359137955b87#diff-0affe5ad0da3e645d904725e33155764
