### ISSUE TITLE
How do I define steps?

### ISSUE THREAD

**Issue by BevanR** [TradeMe/tractor#129]
I got tractor server running, configured it to point at my custom domain, created a feature file and ran it.  Tractor choked on the pending step definitions.  I couldn't see a way to define steps in the UI.

Do I have to do that part in code in `tractor/step-definitions/*.step.js`?  Is this a standard Cucumber JS environment?  Do those docs apply?

(I have used Gherkin and Cucumber JS a lot already.)

**Comment by phenomnomnominal** [comment]
I'm going to use these issues as starting points for proper docs. Would you also like quick answers now?

**Comment by BevanR** [comment]
Great idea.

Quick answers would be great too.

**Comment by phenomnomnominal** [comment]
Sweet - I'll give you a quick overview of everything here to step you needing to jump around issues. I should preface this by saying that you probably want to be on `tractor@latest` cause that's the one that works with Angular (2+).

When you create and save a feature, it generates each of the .step.js files for you. Tractor enforces you to use those files in a specific way.

GIVEN steps are always used for setting up mock data
WHEN steps perform actions on components
THEN steps perform assertions on components

When you click on the "Step Definitions" tab, it should list the created steps on the right, and opening one of them should allow you to implement the step.

For a GIVEN step you will be able to add configuration for how to handle XHR calls. That can be one of two things, a "passthrough" which makes a real call (for full E2E tests) or a "mock" which allows you to respond to a call to a given URL (defined by a regexp) with some JSON. To do the latter you will need to add some mock JSON by using the "mock data" tab. 

For WHEN and THEN steps you perform actions and assertions on components. This means you need to create components first. Components (which are just Page Objects, I'm going to rename them soon) define the actions of different elements of the application, and also the things you would like to validate.

Components have "elements" and "actions". Elements are defined with a name and a protractor selector. Currently you can use all the options from NG1, but going forward I'd suggest just using CSS. Actions then perform interactions on the elements of the component, allowing you to build up complexity. You can also define "parameters" for actions, which let you pass through values from your steps.

Hopefully that gets you started?
