### ISSUE TITLE
Remove inner/outer HTML methods

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#131]
innerHTML & outerHTML are no longer supported. We need to remove them from the UI, 

Moving forward we can still use getAttribute('innerHTML') if we need to use that method.

**Comment by phenomnomnominal** [comment]
Fixed in https://github.com/phenomnomnominal/tractor-plugin-page-objects/commit/c881486637f31bfde70eb065478db65bbcbc4c73
