### ISSUE TITLE
Scenario Outlines (Parameters)

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#14]
I want to be able to create a single reusable scenario outline - then reuse it with parameters.
A Gherkin Scenario Outline means the basic parameterised gherkin syntax is run multiple times, as it works through a table of parameters.
EG.

 Scenario Outline: I can see a paginated list of a member's feedback (more than 10 pages)
   Given I'm viewing my member feedback
   And   I have more than 500 feedback across "<FeedbackType>" feedback types
   When  I'm on page 1 of the "<FeedbackType>" feedback summary page
   Then  I can see pagination links for pages 1-9
   And   I cannot see a left pointing link
   And   I can see a right pointing link
   But   I cannot see a link for page 10
   When  I click the page 7 link
   Then  I can see a link for page 10
   But   I cannot see a link for page 1

   Examples:
   |FeedbackType|
   |All         |
   |Selling     |
   |Buying      |

**Comment by jonoelkin** [comment]
I should be able to use Parameters as both inputs and expectations on a page too

**Comment by ghost** [comment]
? bits of this functionality is there but not exposed

good feature to have, but low priority for v1
i.e. nice to have

**Comment by phenomnomnominal** [comment]
Closing this as `@tractor-plugins/features` is now deprecated.
