### ISSUE TITLE
Step definition files not updated when moved on the front end.

### ISSUE THREAD

**Issue by snixers** [TradeMe/tractor#151]
I created a bunch of step definitions and then structured them into 'GIVEN', 'WHEN' and 'THEN' folders.  My test then failed as the step definitions couldn't either the object document or the mocked data as it was now 3 directories up instead of 2.

In the image below I added the additional directory manually.
![image](https://user-images.githubusercontent.com/14268474/42251731-1fa8ee0c-7f8d-11e8-9c58-e0fd0f1bbe8b.png)

**Comment by phenomnomnominal** [comment]
Closing this as `@tractor-plugins/step-definitions` is now deprecated.
