### ISSUE TITLE
Add information and screenshot on failure

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#17]
When a step fails, save the test steps and reason for failure somewhere. This will help identify the reason for a failure with much more ease. A screenshot can be super handy too (at the step it failed on)

**Comment by jonoelkin** [comment]
It is dumb and time consuming having to run a test suite again just to find the fail point of one test.

**Comment by ghost** [comment]
Done as part of reporting by @galileo1
will be included in v1
