### ISSUE TITLE
View definitions from Gherkin page

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#18]
Make it so I can link from the gherkin to the related step definitions only.
It is likely when I'm dealing with a gherkin, i'm not interested in other unrelated step definitions - so dont show them to me.
It would be a good way of limiting/finding step definitions which i currently am dealing with.

**Comment by ghost** [comment]
Quick win - should just be a link
Include in v1
When we say Gherkin page we mean feature page
