### ISSUE TITLE
Pause on failure option

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#19]
Rather than allowing a test to move on and fail. It would be good to pause on failure - this would help see the state the test was in at failure. Better for debugging.

**Comment by ghost** [comment]
Pause _during_ test
We are capturing the screenshot of the failure
We use this at the moment, but not exposed to UI
Yes for v1

**Comment by Galileo1** [comment]
@jonoelkin as per our discussion this capability will be enabled on single feature run and will not work for  full tractor run. Acceptance Criteria - 
In order to reproduce the error for a failed feature
As a user of tractor 
I want to debug a single feature
