### ISSUE TITLE
Ignore error option

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#22]
It is handy sometimes to be able to create a step which is there for 'just in case' type situations on setup. I may be interested in getting to a certain page, and the state of the page beforehand does not matter to me - so putting in a step for multiple states of that page might be useful. So i'll have 2 steps, one of which will always fail - depending on the page state. I do not want my test to fail in that situation though. So, a ignore failure type of thing can be quite useful.
Good to know somethign failed, but i may not want the whole test to fail because of it

**Comment by ghost** [comment]
This sounds like being able to branch in a test - execute an alternate pathway.
I think with mocked data this isn't a high priority

v2 if more requests for it
