### ISSUE TITLE
Top up account with credit card - new account balance does not up date 

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#23]
Currently working on {Gherkin - MtmcreditAccount}

When you successfully top up your account and you are taken back to the MTM summary page, i would expect my balance to be updated by the amount i credited. 

So for this example balance before top up $-0.50 expected balance after top up $4.00

Actual balance $-0.50

**Comment by ghost** [comment]
To do with two calls on the same page
We think that doing another given will work

@TRBPRO23 to investigate and see

**Comment by ghost** [comment]
Close this and refer to #43
