### ISSUE TITLE
Add in Background steps

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#24]
In Gherkin you can write Background steps, which are used as the setup given statements for a feature - the scenario steps pick up from when the background ones end. We should add this in to Tractor, to stop us having to add in the same steps for each scenario.

eg.

Feature: List a general item
  In order to sell multiple quantities of an item
  As a trade me member
  I want to be able to create multiple quantity listings

  Background:
    Given I'm logged in
    And   I'm an authenticated member
    And   I'm on the sell page
    And   I satisfy all required fields
    And   I have chosen a quantity of items to sell
    But   I have not added a photo

  Scenario: I can list an MQL item without a photo
    Given I have not added a photo
    When  I click the <next> button
    Then  I'm taken to the confirmation screen
    When  I click the <confirm> button
    Then  My listing is created
    And   I'm shown a success screen
    And   My listing is for multiple quantities

  Scenario: I can list an MQL item without a photo
    Given I have added a photo
    When  I click the <next> button
    Then  I'm taken to the confirmation screen
    When  I click the <confirm> button
    Then  My listing is created
    And   I'm shown a success screen
    And   My listing is for multiple quantities

**Comment by ghost** [comment]
Meta givens / reuse of a set of givens
Sounds like a good thing to have, but we haven't really needed it yet

The folder structure is helping 

v2

**Comment by phenomnomnominal** [comment]
Closing this as `@tractor-plugins/features` is now deprecated.
