### ISSUE TITLE
UI changes wanted

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#25]
![ui_-_component_1](https://cloud.githubusercontent.com/assets/10913287/6607934/bae5fc3e-c8a7-11e4-9aa4-d830304e7db4.png)
![ui_-_component_2](https://cloud.githubusercontent.com/assets/10913287/6607935/bb116860-c8a7-11e4-8927-96d1b8d4463c.png)
![ui_-_gherk_1](https://cloud.githubusercontent.com/assets/10913287/6607936/bb24a114-c8a7-11e4-8472-17d0005eed90.png)
![ui_-_mockdata_1](https://cloud.githubusercontent.com/assets/10913287/6607937/bb2620ca-c8a7-11e4-8abd-fb043ae4b93f.png)
![ui_-_step_1](https://cloud.githubusercontent.com/assets/10913287/6607939/bb2a81d8-c8a7-11e4-9411-940371eaabe4.png)
![ui_-_step_2](https://cloud.githubusercontent.com/assets/10913287/6607938/bb284670-c8a7-11e4-9c6f-55b8264ef229.png)
I

**Comment by ghost** [comment]
@yemo to investigate and look at if there is any critical stuff hidden in here

We want to close this case
We know the baby is ugly, and we want to do a design sprint later #GreenForEver

**Comment by yemo** [comment]
all links will be done with #18

**Comment by yemo** [comment]
folder structures already done.

**Comment by yemo** [comment]
Auto complete / auto suggestion will be done at V1

**Comment by yemo** [comment]
Copy and Delete component option has already done.

**Comment by yemo** [comment]
App root url has already fixed

**Comment by yemo** [comment]
has 'delete' for Step Definition. however, I don't think 'copy' is a good idea.

**Comment by yemo** [comment]
Reviewed all issues and new features in this issue. and new issues have been created for future development. This issue can be closed.
