### ISSUE TITLE
Writing Gherkins: The I want field needs to be bigger 

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#3]
The I want field needs to be bigger so i can see all the text that i have written in that field. 

This also applies to the Step: within the step declarations. 

![image](https://cloud.githubusercontent.com/assets/10700614/5894050/8a1670c8-a55e-11e4-8e3b-bed59df43d19.png)

**Comment by jonoelkin** [comment]
All text fields and titles etc need to be bigger. They should wrap or something, so that you can see all of what is written.

**Comment by ghost** [comment]
@phenomnomnominal close this
