### ISSUE TITLE
Add new button for Component, feature, step definitions and Mock data

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#34]
Could a add new button be added to Component, feature, step definitions and Mock data. 

As after adding a new component/feature/StepD/MockD - To create a new file you have to click out of the area you are working in and then click back. 

![image](https://cloud.githubusercontent.com/assets/10700614/7558349/337d3810-f7f6-11e4-8ffb-f3ddae28d507.png)

**Comment by phenomnomnominal** [comment]
Done!
