### ISSUE TITLE
When deleting mock data from step definitions - tractor is deleting removing a bunch of files

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#35]
Steps to recreate:
I have step definitions that i have attached mock data too
I then remove the mock data and save
Then i get the below error in the console 

![image](https://cloud.githubusercontent.com/assets/10700614/7643454/bd2874b8-faed-11e4-88ac-3be6e388e6df.png)

It seems that Tractor has deleted a bunch of files 

![image](https://cloud.githubusercontent.com/assets/10700614/7643458/d61ce4ea-faed-11e4-9d85-73e568f6d821.png)

Will add more detail if i keep getting this issue.

**Comment by TRBPRO23** [comment]
I just had the same happen again when making a change to a Gherkin

![image](https://cloud.githubusercontent.com/assets/10700614/7643745/354927a6-faf0-11e4-9449-e9c932facb8a.png)

**Comment by TRBPRO23** [comment]
This seems to be working a little better know, Elwyn reinstalled some parts of tractor and it seems better now. I will update this ticket if i get it again.

**Comment by TRBPRO23** [comment]
So i have figured out what is causing this issue, if you save your changes and then click somewhere else, then tractor fails and changes files. 

A possible fix could be to have a saving state so no action can be taken until the save has been completed.

**Comment by phenomnomnominal** [comment]
I know this one sucks real bad, but I know what it is and I have a fix for this! Will get onto it soon as I'm back!

**Comment by phenomnomnominal** [comment]
This shouldn't happen now.
