### ISSUE TITLE
updating a component after it has already been added to a step definition, breaks that step definition 

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#37]
Given i have all ready added a component to a step definition. 
I then rename that specific component and save my change.

When i go to view that step definition after the change i get a blank page.    

![image](https://cloud.githubusercontent.com/assets/10700614/7673134/ce15ebd2-fd60-11e4-8572-7032d3ee5d5e.png)

**Comment by ghost** [comment]
v1
Still an issue we care about

Bit of a rework on how references between files are tracked to eachother
tiny bug

**Comment by phenomnomnominal** [comment]
Closing this as `@tractor-plugins/step-definitions` is now deprecated.
