### ISSUE TITLE
We have to manually add a \ to the URL path

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#41]
When we save  mock data it automaitcally adds the \/, but it doesn't add it for special characters. 

example: \/ngapi\/v1\/search\/general.json?category

Should have one: \/ngapi\/v1\/search\/general.json\?category

**Comment by ghost** [comment]
Done! but @phenomnomnominal still wants to think
Has been developed in to v1

**Comment by TRBPRO23** [comment]
Fixed
