### ISSUE TITLE
Having issues when given data is required and used

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#43]
I am creating tests where i am removing and item from a list.

So i have the first given which has data (a) with a total of 5 items on this list. 
I then remove an item from the list, which then should call data (b) which has a total of 4 items. 

This is not happening. 

What is happening is that tractor does not seem to be picking up on data (b) and is using data (a), so making it seem that the data has not been removed.

**Comment by ghost** [comment]
@TRBPRO23 to check it and see if it's fixed

To be fixed in v1

**Comment by TRBPRO23** [comment]
This is still not working

**Comment by phenomnomnominal** [comment]
@TRBPRO23 does this work now?
