### ISSUE TITLE
Moving component into a folder does not update step definition

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#45]
If you have a component, and then you move it into a folder within the component area, then the step definition which references that component is not updated to reflect the new component location (misses the '../../../' stuff).

**Comment by ghost** [comment]
We think this mostly works
Over to @jonoelkin to see if he can make the bug happen / close it
One year ago - reproduction challenge!

**Comment by yemo** [comment]
Moving component location, edit component names and component folder names are reflect Step Definition now. this issue can be closed.
