### ISSUE TITLE
Cannot use 'false' in an expectation

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#47]
In order to confirm something is NOT selected, I want to be able to set an expectation with a condition of 'equal' with the expected result of 'false'.
This will be used a lot of the time for negative tests.

**Comment by ghost** [comment]
This case should be about handling the boolean 'false'

**impact** high
v1

**Comment by yemo** [comment]
spoke to jono, this bug is duplicate with #71, it can be closed.
