### ISSUE TITLE
Make an Ignore Failure/error option

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#48]
Sometimes I want to add in a step which will deal with unforseen situations such as local storage making a continue/start over pop-up appear when going to sell something.
It would be good to be able to put a "run and ignore error" function into Tractor so i can add a step but it not matter if it fails or not.

**Comment by ghost** [comment]
Curious if we should be having 'run and ignore' tests, and when this happens
@jonoelkin to convince me when it's needed

Populating local storage _does_ sound like something we should have
Very specific to one feature (continuing interrupted sell process) 
Thinking v2
