### ISSUE TITLE
Make it so that I can use numbers in a step definition

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#49]
I want to be able to have numbers in my step definitions. Like this... "I enter a start price less than 10 percent of the reserve"
Currently if i have that, Protractor screws out, exits and says there is a bug.
I have to write this instead, to make it work: "I enter a start price less than ten percent of the reserve"

**Comment by ghost** [comment]
totes works
![image](https://cloud.githubusercontent.com/assets/12591741/16401612/1bcd6002-3d3a-11e6-9a0f-52f394b9d677.png)

**Comment by ghost** [comment]
@jonoelkin to close this
