### ISSUE TITLE
Want the ability to use/send the 'Enter' button 

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#58]
So i'm not limited to using a button to click, like when i'm on a mobile, I want to be able to interact with the page using the enter button on a keyboard. 

Something like...

ptor.actions().sendKeys(protractor.Key.ENTER).perform();

**Comment by ghost** [comment]
question - is pressing the enter key part of submit? field tab progression? 
I think we need to talk to the Tangrammers and UX about when enter would/wouldn't be used

I feel like if you're in a form and press enter, it will submit the form
If that's the case, it's only one test to check enter submits the form/button?

**Comment by ghost** [comment]
@jonoelkin to follow up with people

**Comment by elwynelwyn** [comment]
This came up once when a form was NOT submitting by pressing enter, as it should. We wanted to add a test over it to ensure this functionality did not regress.

**Comment by jonoelkin** [comment]
last i checked this was not fixed. Varun - please show me it working before i close it

**Comment by phenomnomnominal** [comment]
Fixed in https://github.com/phenomnomnominal/tractor-plugin-browser/commit/efb7b10a9624c85402fd34e2616d52442701991e#diff-3a228a7bd867db176070240e4e508011R9 ❤️
