### ISSUE TITLE
Grouping step definitions by the Gherkin features 

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#6]
On the Step definition page it would be cool if they were grouped by the Gherkin Features. For example we currently have 3 Gherkin files that i am working from 

![image](https://cloud.githubusercontent.com/assets/10700614/5908785/78e6e2cc-a60f-11e4-97e6-e52adad51f04.png)

When you click into Step definitions it is just order alphabetically, so as the files grow it will become harder to quickly find what you are looking for. 

![image](https://cloud.githubusercontent.com/assets/10700614/5908804/a24c8f54-a60f-11e4-81cc-9a8cb21dbbb1.png)

**Comment by ghost** [comment]
We have folders now
the future is here

@phenomnomnominal close this too
