### ISSUE TITLE
If you change something on an existing Gherkin another Step Definition is added 

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#7]
If i have an existing Gherkin that i am working on and i go make a change to this Gherkin. Another step definition is being added. Please find example below

Changed title of Gherkin from When I Enter A Page To Browse Too to when I enter a page into Go To Page. I would expect my existing Gherkin to update with these changes. What is happening i am getting a new definition file. 

![image](https://cloud.githubusercontent.com/assets/10700614/5911575/207077d0-a62c-11e4-9855-bf3e96c50434.png)

**Comment by ghost** [comment]
Still an issue. Will create noise / more step definitions that we need
**impact**: minor

**Comment by TRBPRO23** [comment]
Still an issue

**Comment by yemo** [comment]
it became a big noise now, we have 262 scenario with 1460 step definitions. large number of step definitions are not used, and cannot remove at the moment. Because we don't know whether it is used or not.

**Comment by phenomnomnominal** [comment]
Closing this as `@tractor-plugins/step-definitions` is now deprecated.
