### ISSUE TITLE
Timing issue when trying to locate element. 

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#70]
We have a test which is opening the lightbox modal and then trying to click next and prev buttons within the modal. But there seems to be a timing issue as sometimes Tractor can’t find the next and prev buttons. 

We were wondering if something could be added to the When step so tractor checks the element once it is visible?

**Comment by ghost** [comment]
Hey @TRBPRO23 
@phenomnomnominal thinks your test has a bug in it.
#WorksOnHisMachine

**Comment by TRBPRO23** [comment]
No longer an issue
