### ISSUE TITLE
Request: Negative checking capability

### ISSUE THREAD

**Issue by edstewart** [TradeMe/tractor#71]
The ability to check the absence of something using Tractor would be useful. 

For example, we can check that the 'In Trade' ribbon is displayed for an In Trade member, but we can’t check that it isn’t displayed for a normal member. Aside from checking for the absence of the icon, there is no way for Tractor to determine that the member is not In Trade, and so no way for us to check that this logic is achieved in the front end presentation.

**Comment by ghost** [comment]
Definitely v1
**impact** high

either will be super easy, or ... not

**Comment by Galileo1** [comment]
isPresent has been added to tractor v0.8.4 element locator

**Comment by edstewart** [comment]
'isPresent' added - issue appears to have been addressed. 

Closing this request.
