### ISSUE TITLE
Request: Support additional browsers

### ISSUE THREAD

**Issue by edstewart** [TradeMe/tractor#74]
If Tractor could run the checks on multiple browsers, the ROI on the effort of creating them would be far greater.

**Comment by phenomnomnominal** [comment]
This one has nothing to do with Tractor. Protractor can use multiple browsers, so you just have to modify the protractor.conf.js in a project to include other browsers and make sure the right webdriver extensions are installed.

There's a tonne of stuff about it online, e.g. [this](http://stackoverflow.com/questions/19227583/e2e-testing-in-protractor-using-firefox-or-safari) or [this](http://stackoverflow.com/questions/26395216/with-protractor-how-to-setup-internet-explorer-configuration)

**Comment by edstewart** [comment]
OK, that's great! Thanks for the info =) 

We were unaware of this, as Protractor and its capabilities are not things we're familiar with at present... Can this info please be added to the Tractor manual? It currently only discusses Chrome, which is one of the reasons we had the impression that was the only browser supported.

One further question: Will we be able to run Tractor on multiple browsers from a single click of 'Run Protractor', without updating the config each time?

**Comment by phenomnomnominal** [comment]
Yep, looks like it [according to this](http://stackoverflow.com/questions/20692008/protractor-run-multiple-tests-in-parallel-on-different-browsers/21911006#21911006)

I'll talk to Tyrone about getting it up and running and out to default on Preview.

**Comment by edstewart** [comment]
Awesome! Thanks again for the info =)

**Comment by TRBPRO23** [comment]
Updating the config and it spun up on both browsers. But it doesn't run on firefox, just hangs. I will have a look to see if it is a quick fix to get it going.
