### ISSUE TITLE
Request: Support additional breakpoints

### ISSUE THREAD

**Issue by edstewart** [TradeMe/tractor#75]
Having Tractor capable of running across the different breakpoints would validate the effort to create checks by increasing automation coverage and reducing manual checking time.

**Comment by ghost** [comment]
Screen sizes/resolutions
- be able to ta a test as specific to a breakpoint (include/exclude)
- be able to have a global setting that all tests run against

already have mechanism for going FULL SCREEN, so in theory not major to implement

definitely for v1

**Comment by phenomnomnominal** [comment]
Done with `tractor-plugin-screen-size`
