### ISSUE TITLE
Bug: Invalid characters

### ISSUE THREAD

**Issue by edstewart** [TradeMe/tractor#76]
Some characters are invalid in certain fields, but the validations to prevent saving them are not consistent. 

For example, if I enter invalid characters in a component, element, action or feature name, I’m prevented from saving it until they are removed. I’m not prevented from saving a step declaration with invalid characters, but when I try to access it in Step Definitions it will not display until the invalid characters are removed.

**Comment by ghost** [comment]
@edstewart what are you trying to achieve when using invalid characters?
Is that part of the test?

**Comment by edstewart** [comment]
@seancresswell Not directly – in this case I was trying to name a step declaration to directly reflect its content: check a 'Save X%' ribbon is being displayed. The issue was not knowing up front that the step wouldn't be usable downstream.
