### ISSUE TITLE
The ability to tell what tests are pending/skipped/passed

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#8]
It would be good if we could tell what tests are in a pending/skipped/passed state. At the moment there is no way to tell. 

![image](https://cloud.githubusercontent.com/assets/10700614/5912103/a6e79f8a-a633-11e4-9586-ef19a704934c.png)

**Comment by ghost** [comment]
Command line gives us this information and reporting has been improved.
No longer a major

@phenomnomnominal close this - other reporting improvements will cover this
