### ISSUE TITLE
EMFILE too many files open - switch from fs to graceful-fs

### ISSUE THREAD

**Issue by elwynelwyn** [TradeMe/tractor#90]
On Windows there is a reported error of `EMFILE too many files open`.

A fix might be to depend on `graceful-fs` and use it in all the places `fs` is currently used. The API is the same so it should be a drop-in replacement.

**Comment by TRBPRO23** [comment]
Be good to get this fixed, as it is pretty annoying.  Tends to happen every time i go Tractor Start, sometimes it happens 4 + times before Tractor runs/

**Comment by Galileo1** [comment]
fix implemented in version 0.8.5
