### ISSUE TITLE
Block ad requests to improve speed

### ISSUE THREAD

**Issue by ghost** [TradeMe/tractor#93]
Tyrone mentioned that if he runs tractor with an adblocker, speed improves dramatically

It would be cool if there was an run the tests with an adblocker enabled (this may already exist)

But - also and ability to serve 'generic' ads (in the correct sizes) rather than getting the ads from google would be great.
This may be a plugin outside of Tractor.

**Comment by Galileo1** [comment]
Setting a ablocker extension in browser profile capabilities should do the job.
documentation says the extension should not be a .crx file rather a base64 ecoded file in local repository.

In protractor.config.js file -

capabilities {
    'browserName': 'chrome',
    'chromeOptions': {
    'args': ['--load-extension=' + extensionPath]
    }
}

 or

capabilities: {
    'browserName': 'chrome',
    "chromeOptions": {
     extensions: [base64 encoded file], 
    }  
  }

**Comment by TRBPRO23** [comment]
Got this working on my machine by adding the following 

```
capabilities: {
    'browserName': 'chrome',
    'chromeOptions': {
      'args': ['--load-extension=' + 'C:/Users/tbiddle/AppData/Local/Google/Chrome/User Data/Default/Extensions/gighmmpiobklfepjocnamgkkbiglidom/3.2.0_0']
    }
},
```

This isn't a final solution as this file location is specific to my PC. The other option would be to save the extension within the project folder and reference it that way. This approach again is not ideal having a 3rd extension within our project.

**Comment by TRBPRO23** [comment]
Run with no ad blocker 
227 scenarios (2 failed, 225 passed)
2633 steps (3 failed, 6 skipped, 2624 passed)
40m23.070s

Run with ad blocker 
227 scenarios (2 failed, 225 passed)
2632 steps (2 failed, 4 skipped, 2626 passed)
30m31.761s

**Comment by Galileo1** [comment]
the crx chrome extension is now being picked up from the shared drive. From tractor perspective it should be closed as the solution is working.

**Comment by Galileo1** [comment]
Mr @TRBPRO23 - Do you have any more thoughts about it or you are happy with what we currently have??

**Comment by TRBPRO23** [comment]
It is working for now, but not the ideal solution, I think we still need to look at severing static ad's in test, as we still experiencing timeout issue when running tests's without ad blocker.  

But the ad blocker work around will do for now.

**Comment by phenomnomnominal** [comment]
Static ads would be extra good for VR cause then we can actually check they're displaying instead of just ignoring them

**Comment by phenomnomnominal** [comment]
I'm going to consider this solved. Loading the ad blocker works well enough. We should doc it though.
