### ISSUE TITLE
Multi instances: Reporting

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#94]
I want to be able to spin up Tractor across multiple instances using this...

```
capabilities: {
'browserName': 'chrome',
shardTestFiles: true,
maxInstances: 1
},
```

Problem is, when tractor finishes running them, there is no overall report for the run. There are individual reports created after each feature has been run, but that is not much use (too difficult and time consuming to see total failures and what they were). I want to be able to run my entire tractor suite with multiple instances, the n have a nice report at the end like i would if i ran it like normal (one instance).

**Comment by phenomnomnominal** [comment]
Fixed with https://github.com/phenomnomnominal/tractor-plugin-cucumber/commit/e200d4d4362fdcb1286b98b13bea084796cd0c40
