### ISSUE TITLE
UI running mode enhancements

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#96]
1. I want to be able to choose if I run (at either feature or entire suite level) my tests with debug mode (pausing run on a failure) on or off on the UI
2. I want to be able to set how many instances of chromedriver i want to run my tests on, in the UI

**Comment by Galileo1** [comment]
@jonoelkin - The first one has been completed and released in verison 0.8.5.Can we please close this issue and keep #95 open for point 2. I have already added comment to that issue. thanks
